# Generated by Django 6.0.6 on 2026-09-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='Leave blank to receive no Telegram reminders.', max_length=32, verbose_name='Telegram chat ID'),
        ),
    ]
