# Generated by Django 6.0.6 on 2026-08-22 01:16

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.UUIDField(default=main.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('text', models.CharField(max_length=200, verbose_name='commitment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'commitment',
                'verbose_name_plural': 'commitments',
                'ordering': ['-created_at'],
            },
        ),
    ]
