# Generated by Django 6.0.6 on 2026-08-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='date',
            field=models.DateField(db_index=True, verbose_name='date'),
        ),
    ]
